name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@sarantrs'
      
      - name:  Setting npm credentials to publish
        run: npm config set //npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}
      - name: Check if react-library-rollup version has been updated
        id: react-library-rollup
        uses: EndBug/version-check@v1
        with:
          diff-search: true
          file-name: package.json
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependency
        run: npm install
      - name: Build application
        run: npm run build
      - name: Publish react-library-rollup to GitHub Packages
        if: steps.react-library-rollup.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN }}